# This file is a template, and might need editing before it works on your project.
# Lifted from: https://about.gitlab.com/2016/03/10/setting-up-gitlab-ci-for-ios-projects/
# This file assumes an own GitLab CI runner, setup on an OS X system.
stages:
  - build
  - review
 # - archive

build_project:
  stage: build
  script:
    - xcodebuild clean -project BaseProject.xcodeproj -scheme BaseProject | xcpretty
    - xcodebuild test -project BaseProject.xcodeproj -scheme BaseProject -destination 'platform=iOS Simulator,name=iPhone 6s,OS=9.2' | xcpretty -s
  tags:
    - ios
    
sonar_review:
    stage: review
    script: 
        - sonar-scanner
    tags:
        - ios

#archive_project:
#  stage: archive
#  script:
#    - xcodebuild clean archive -archivePath build/ProjectName -scheme SchemeName
#    - xcodebuild -exportArchive -exportFormat ipa -archivePath "build/ProjectName.xcarchive" -exportPath "build/ProjectName.ipa" -exportProvisioningProfile "ProvisioningProfileName"
#  only:
#    - master
#  artifacts:
#    paths:
#    - build/ProjectName.ipa
#  tags:
#    - ios_9-2
#    - xcode_7-2
#    - osx_10-11
