# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end
  lane :beta do |values|
    # Fabric generated this lane for deployment to Crashlytics Beta
    # set 'export_method' to 'ad-hoc' if your Crashlytics Beta distribution uses ad-hoc provisioning

    ##### increase build number by 1 ####
    increment_build_number(xcodeproj: "BaseProject.xcodeproj")

    #### build project ####
    build_app(scheme: 'BaseProject',
		 export_method: 'development',
		 clean: true)

    #### Setup Crashlytics ####
    #emails = values[:test_email] ? values[:test_email] : ['srujank@boston-technology.com'] # You can list more emails here
    #groups = values[:test_email] ? nil : nil # You can define groups on the web and reference them here

    crashlytics(api_token: '24faf2a83c3fd824044bfbcc2b7b4be24b8b28a1',
             build_secret: 'c33a12b8c295fb1886720465e29ecebd81ee14abcd7c7e2f37553d09a685b735',
                   emails: ["srujank@boston-technology.com","tushark@boston-technology.com","surenders@boston-technology.com"],
                   groups: groups,
                    notes: 'Distributed with fastlane', # Check out the changelog_from_git_commits action
            notifications: true) # Should this distribution notify your testers via email?


    #### push to gitlab #####
    version = get_version_number(xcodeproj: "BaseProject.xcodeproj")
    build_number = get_build_number(xcodeproj: "BaseProject.xcodeproj")
    commit_version_bump(
      message: "Increased build version to : " + version + "." + build_number,
      force: true
    )
    push_to_git_remote(
                remote: "origin",         # optional, default: "origin"
                local_branch: "Manish_develop",  # optional, aliased by "branch", default is set to current branch
                remote_branch: "Manish_develop", # optional, default is set to local_branch
                force: true,    # optional, default: false
                force_with_lease: true,   # optional, default: false
                tags: false     # optional, default: true
    )
    # for all available options run `fastlane action crashlytics`

    # You can notify your team in chat that a beta build has been uploaded
    # slack(
    #   slack_url: "https://hooks.slack.com/services/YOUR/TEAM/INFO"
    #   channel: "beta-releases",
    #   message: "Successfully uploaded a beta release - see it at https://fabric.io/_/beta"
    # )
  end	

end
